### PR TITLE
Added instructions for requiring the gem

### PR DESCRIPTION
**Pull request by boomshadow**
I'm still fairly new using Grape. How to require the gem wasn't obvious to me. I had to dig through other peoples' example code to find the answer. I figured it would be best if the instructions were a little clearer for newer people like myself. Heh heh.

### CODE REVIEW

**Comment by ridiculous** [comment]
Are you not using Bundler?

**Comment by boomshadow** [comment]
I am using Bundler. But without adding the `require 'grape/middleware/logger'` to my config.ru, I will get an uninitialized constant error:

    <class:API>': uninitialized constant Grape::Middleware::Logger (NameError)

**Comment by ridiculous** [comment]
So when do you call `Bundler.require`? That should load all dependencies listed in Gemfile. It should be called before loading your main app (e.g. `API`)

**Comment by ridiculous** [comment]
Did that work for you? I'd prefer not to add instructions unless it's really needed. Let me know, otherwise i'll close this issue. Thanks!

**Comment by ridiculous** [comment]
Closing. Feel free to reopen if you're still having issue. Thanks

**Pull request closed without merging**
