### PR TITLE
allow install on grape 1.0

### PR DESCRIPTION
**Pull request by badlamer**

### CODE REVIEW

**Comment by ridiculous** [comment]
oh snap, they finally release v1! 🎉 
Does the logger with v1?

**Comment by badlamer** [comment]
@ridiculous grape recommended this gem for logging

**Comment by ridiculous** [comment]
I mean, have we tested it with v1? I can try to test it today, but we need to verify this change

**Comment by badlamer** [comment]
@ridiculous already in production! 

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ridiculous** [comment]
Excellent! Thanks

**Comment by ridiculous** [comment]
Published as v1.9.0

**Pull request merged**
